[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeepelin=lib/openzeepelin-contracts']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
